### ISSUE TITLE
Implement Registration and Login system 🔐

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#203]
### Initial note
We can't implement this feature until @MarcoBuster provides us a server.

#### Requirements
- The user must be able to register with his @studenti.unimi.it email address (this is the only email address allowed, to avoid possible bots and people who are not students).
- The logged user will be able to see his username in the top-right corner of the headerMenu.
- The not logged user will see "Register" button in the top-right corner of the headerMenu.

#### Purpose of this feature
The logged-user will be able to give an opinion about the courses (maybe I'll implement other features in the future).
I will link the relative issue of the feature when i'll create it.

#### Visualization and code
- [ ] Add in the headerMenu "Register" button if the user is not authenticated and "Login" button if the user is authenticated;
- [ ] Decide how to handle visualization on mobile devices (I suggest a Persona component without text);
- [ ] Implement dialog that allows the user to register;
   - [ ] Insert the form and required fields errors handling;
   - [ ] We must show how we treat personal data;
   - [ ] Fields must be required, so I suggest [#Text field error message variations](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) if they support the avoiding of submitting the form;
   - [ ] Email field could have this [suffix](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) with 
   @studenti.unimi.it since it is required.

**Comment by MarcoBuster** [comment]
This feature needs C.A.N.'s approval, and it's not high priority.

**Comment by Giuseppetm** [comment]
> This feature needs C.A.N.'s approval, and it's not high priority.

It's been days since I requested this approval.
I would have expected an answer or a minimum consideration in this regard, since it has not arrived I have started to draw up the requirements. After discussing with Silvio we both agreed that this feature on our site is the one that would take us a step up from any other such platform. So, you might as well propose it to the council and let Silvio give the reasons we talked about the other day.

**Comment by Giuseppetm** [comment]
Regarding the high priority of this feature, I am the one who decides this as a feature of the website. I believe it has a high priority as it is of high importance that students can make their own judgments in terms of non-textual assessments as soon as possible and especially before the start of a new academic year.

In this regard it would be correct that other members of this network also begin to fulfill their duties. I am the only developer who is implementing new features, and you have the courage to block my proposals for new features only because in all these days you have not been able to propose this to the council, and you have not been able to go and find if effectively allowing a student to give a grade from 1 to 10 on an aspect of an educational course anonymously whether it is a form of abuse or not.

**Comment by Giuseppetm** [comment]
I will close this until we decide what to do.
