### ISSUE TITLE
Homepage with recent news

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUnimi/website#22]

**Comment by MarcoBuster** [comment]
How would you take news from unimia? And most importantly, what news are on the unimia panel? I dont't see any.
Maybe you mean the unimi.it website.

**Comment by Giuseppetm** [comment]
@MarcoBuster

**Comment by georgiani** [comment]
Ma che cazzo fai?

**Comment by MarcoBuster** [comment]
@georgiani

**Comment by MarcoBuster** [comment]
What's happening? Where is Bugo?

**Comment by georgiani** [comment]
> What's happening? Where is Bugo?

Donde esta Bugo?

**Comment by busolind** [comment]
> What's happening? Where is Bugo?

Let's go find Bugo

**Comment by MarcoBuster** [comment]
> > What's happening? Where is Bugo?
> 
> Let's go find Bugo

The bad intentions and the rudeness..

**Comment by Giuseppetm** [comment]
Beneh, facciamo una pausah.

**Comment by georgiani** [comment]
<img src = "https://pyxis.nymag.com/v1/imgs/d6a/dc7/4a5001b7beea096457f480c8808572428b-09-roll-safe.2x.h473.w710.jpg">

**Comment by busolind** [comment]
> > > What's happening? Where is Bugo?
> > 
> > 
> > Let's go find Bugo
> 
> The bad intentions and the rudeness..

The bad impression you made last night

**Comment by MarcoBuster** [comment]
> Beneh, facciamo una pausah.

Oooohvrr, perché vuoi uscvrireeh?

**Comment by MarcoBuster** [comment]
> > > > What's happening? Where is Bugo?
> > > 
> > > 
> > > Let's go find Bugo
> > 
> > 
> > The bad intentions and the rudeness..
> 
> The bad impression you made last night

Your ingratitude, your arrogance

**Comment by georgiani** [comment]
> > > > > What's happening? Where is Bugo?
> > > > 
> > > > 
> > > > Let's go find Bugo
> > > 
> > > 
> > > The bad intentions and the rudeness..
> > 
> > 
> > The bad impression you made last night
> 
> Your ingratitude, your arrogance

ba dum tss

**Comment by busolind** [comment]
> > > > > What's happening? Where is Bugo?
> > > > 
> > > > 
> > > > Let's go find Bugo
> > > 
> > > 
> > > The bad intentions and the rudeness..
> > 
> > 
> > The bad impression you made last night
> 
> Your ingratitude, your arrogance

You do what you want pushing people around

**Comment by georgiani** [comment]
<table>
<thead>
<tr>
<td>Almeno basi serve a qualcosa</td>
</tr>
<tr>
<td>agaga</td>
</tr>
</thead>
</table>

**Comment by Giuseppetm** [comment]
> Almeno basi serve a qualcosa
> agaga

Bene che hai usato thead e tbody. Altrimenti sarebbero stati 15 punti in meno.

**Comment by Giuseppetm** [comment]
Già presente una issue a riguardo.
