### ISSUE TITLE
Add a new class in "Informatica magistrale" degree course

### ISSUE THREAD

**Issue by ManueleDentello** [StudentiUniMi/website#234]
Degree course: Informatica magistrale 
Name: Sicurezza delle architetture orientate ai servizi
Year: none (not in the study plan)
Semester: 2nd
Ariel link: https://edamianisaos.ariel.ctu.unimi.it/v5/home/Default.aspx
Course link: https://www.unimi.it/it/corsi/insegnamenti-dei-corsi-di-laurea/2021/sicurezza-delle-architetture-orientate-ai-servizi

**Comment by Giuseppetm** [comment]
Thank you mr. Dentello.
