### ISSUE TITLE
Improve readability on Dark Mode

### ISSUE THREAD

**Issue by faro-r** [StudentiUniMi/website#253]
Font tends to be too small and short, and colors should be adjusted to improve overall readability.

**Comment by Giuseppetm** [comment]
Can you provide some examples of low readability?

**Comment by faro-r** [comment]
> Can you provide some examples of low readability?

The slider has fonts that are too small and short, I would use one that tends to be more readable at small sizes. Also, maybe more important, in Dark Mode the margins are invisible

**Comment by faro-r** [comment]
I would use GitHub's default fonts and colors as an example of a readable design

**Comment by Giuseppetm** [comment]
> The slider has fonts that are too small and short, I would use one that tends to be more readable at small sizes. Also, maybe more important, in Dark Mode the margins are invisible

The font sizes are handled by Fluent UI, I just used the standard ones; there are no visibility problems neither from mobile nor from desktop. 

![image](https://user-images.githubusercontent.com/52317197/131247865-62310eda-01a9-4626-bbae-7708e04bd2e2.png)

![image](https://user-images.githubusercontent.com/52317197/131247704-42006cfe-6a66-4352-b6d3-060426c10e26.png)

About the card margins I agree, this is a problem already reported by @manuelelucchi, I will fix it.

> I would use GitHub's default fonts and colors as an example of a readable design

StudentiUniMi has default palettes and default microsoft fonts; If there are display problems on some palettes you can make a pull request regarding the specific file to improve the visualization of some colors about dark mode.

**Comment by Giuseppetm** [comment]
This should be fixed in the new version of the website.
