### ISSUE TITLE
Dynamically update title and description

### ISSUE THREAD

**Issue by MarcoBuster** [StudentiUniMi/website#268]
### Homepage `/home` 
**Title**: `Network StudentiUniMi - gruppi, servizi e molto altro`
**Description (it)**: 
`Sito web ufficiale del Network StudentiUniMi: gruppi WhatsApp rimpiazziati da Telegram, servizi e molto altro. Il network più grande dell'Università degli Studi di Milano.`
**Description (en)**: `Official website of StudentiUniMi Network: WhatsApp groups replaced by Telegram ones, services and much more. The largest network of the University of Milan.`

### Groups page `/courses`
**Title**: `Tutti i gruppi | Network StudentiUniMi`
**Description (it)**: `Tutti i gruppi Telegram per tutti i corsi di laurea (triennali, magistrali, lauree a ciclo unico) dell'Università degli Studi di Milano. Entra, chiedi informazioni e conosci persone nuove grazie al Network StudentiUniMi.`
**Description (en)**: `All Telegram groups for all degree courses (three-year, master, single-cycle degrees) of the University of Milan. Join, ask for information and meet new people thanks to the StudentiUniMi Network.`

### Services page `/services`
**Title**: `Servizi e link rapidi | Network StudentiUniMi`
**Description (it)**: `Stanco dei disservizi di unimia? Da questa pagina alternativa puoi accedere a tutti i link utili dell'Università degli Studi di Milano.`
**Description (en)**: `Tired of unimia's inefficiencies? On this alternative page you can access all the useful links of the University of Milan.`

### Single course page (like `/courses/triennale_informatica`)
**Title**: `Gruppi di Informatica (triennale) | Network StudentiUnimi`
**Description (it)**: `Tutti i link dei gruppi Telegram del corso di laurea di Informatica (triennale) dell'Università degli Studi di Milano offerti dal Network StudentiUniMi. `
**Description (en)**: `All the links of the Telegram groups of the Computer Science degree course (three-year) of the University of Milan. Offered by StudentiUniMi Network.`

### Rules page `/rules`
**Title**: `Regolamento | StudentiUniMi`
**Description (it)**: `Il regolamento ufficiale del Network StudentiUniMi.`
**Description (en)**: `The official rules of the StudentiUniMi Network.`

### Representatives page `/representatives`
**Title**: `Informazioni dall'Ateneo e rappresentanti | Network StudentiUniMi`
**Description (it)**: `Rimani aggiornato con tutte le informazioni e i rappresentanti dell'Università degli Studi di Milano, offerto dal Network StudentiUniMi.`
**Description (en)**: `Stay up-to-date with all the information and representatives of the University of Milan, offered by the StudentiUniMi Network.`

### Organization page `/organization`
**Title**: `Chi siamo | StudentiUniMi`
**Description (it)**: `Chi siamo? Scopri l'organizzazione dietro il Network StudentiUniMi, il più grande network dell'Università degli Studi di Milano.`
**Description (en)**: `Who are we? Discover the organization behind the StudentiUniMi Network, the largest network of the University of Milan.`

## Progress
- [x] Sections title
- [x] Sections description
- [x] Dynamic title based on degree loaded

**Comment by Giuseppetm** [comment]
https://www.npmjs.com/package/react-helmet

This will probably be the library we can use.

**Comment by Giuseppetm** [comment]
@MarcoBuster can you provide descriptions for the sections? (it/eng)

**Comment by MarcoBuster** [comment]
> @MarcoBuster can you provide descriptions for the sections? (it/eng)

No

**Comment by Giuseppetm** [comment]
> > @MarcoBuster can you provide descriptions for the sections? (it/eng)
> 
> No

![image](https://user-images.githubusercontent.com/52317197/133280317-cd9ec17a-10a4-422d-80b1-93f188c002e4.png)

**Comment by MarcoBuster** [comment]
@Giuseppetm descriptions updated
