### ISSUE TITLE
Show some statistics of network usage on the homepage

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#271]
@MarcoBuster can you provide an endpoint to retrieve some stats about the network usage?

**Comment by MarcoBuster** [comment]
> network usage

Sure. Do you prefer MB/s or Mbps?

**Comment by Giuseppetm** [comment]
> Sure. Do you prefer MB/s or Mbps?

I prefer to pass ricerca operativa, thank you.

**Comment by Giuseppetm** [comment]
At the moment we have some numbers on the homepage, maybe there will be some endpoint for this data in the future. Not a priority.
