### ISSUE TITLE
FE hover - onclick bug

### ISSUE THREAD

**Issue by eduardperreca** [StudentiUniMi/website#274]
Change the effect of the colors onclick and hover regarding certain color palettes, the effect that is generated is totally different from what you should expected.

Palette that need to be fixed:
- [x] Red in 4th position
- [x] Peach in 7th position
- [x] Purple in 9th position
- [x] Bordeaux in last position

Example:
https://gyazo.com/9f3a507daaaa225d01969d34bb469f3d

EP

**Comment by Giuseppetm** [comment]
Thanks for the issue; the palettes have never been properly tested and it is a rather unused feature. 

I will fix this in the next weeks.
