### ISSUE TITLE
Margin of the icons in the footer + Use Proprietary icons 

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#295]
- [ ] Utilizzare le icone proprietarie dei servizi linkati
- [ ] Distanziare le icone perché da mobile non si riescono a premere

<img width="351" alt="Screen Shot 2021-09-28 at 15 02 43" src="https://user-images.githubusercontent.com/7923365/135092101-36f667b8-cee5-43a2-81b1-6b5279ca0982.png">

**Comment by Giuseppetm** [comment]
I'm moving this to #280
