### ISSUE TITLE
Move all the settings of the website in the footer and remove the settings panel

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#296]
togliere l'ingranaggio in alto a destra perché da mobile fa casino con il logo del menù

le opzioni dentro l'ingranaggio si possono spostare nel footer

**Comment by Giuseppetm** [comment]
Non so se conviene spostare tutto nel footer; magari posso farlo insieme alla #280.
Ci penso nei prossimi giorni

**Comment by robertopinotti** [comment]
Potremmo tenere il cambio lingua come ultimo elemento del menù nell'header e spostare il tema scuro / scelta del colore nel footer

**Comment by Giuseppetm** [comment]
> Potremmo tenere il cambio lingua come ultimo elemento del menù nell'header e spostare il tema scuro / scelta del colore nel footer

No in caso direi di spostare tutto, l'header è importante che sia pulito e abbia il meno roba possibile. Già l'ingranaggio dava fastidio, meglio lasciare solo il pivot da desktop e l'hamburger da mobile
