### ISSUE TITLE
Add an apposite button to refresh the groups section content

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#297]
quando premo su un elemento del menù dell'header (gruppi, servizi, etc) la pagina non viene refreshata. questo è un problema soprattutto per i gruppi perché viene naturale premere sul link "gruppi" per azzerare la ricerca

esempio: sono in questa pagina https://studentiunimi.it/courses/triennale_sicurezza_sistemi_reti_informatiche, quando premo su "gruppi" non succede nulla

- [ ] When clicking the button of headermenu and you are on the same section, it must reload the page;
- [x] Add a reset button near main title of the groups section.

**Comment by robertopinotti** [comment]
Non si può cambiare il componente? Se premo un link di un menù, in qualsiasi sito web, mi aspetto che faccia il refresh della pagina

**Comment by Giuseppetm** [comment]
> Non si può cambiare il componente? Se premo un link di un menù, in qualsiasi sito web, mi aspetto che faccia il refresh della pagina

Posso risolvere manualmente, in ogni caso per favorire sia gli utenti desktop che mobile direi di usare un pulsante apposito che resetta tutto. In questo modo se sei da mobile non sei costretto ad aprire il menù laterale.

**Comment by Giuseppetm** [comment]
(sistemo comunque il fatto che premendo da' il reset)

**Comment by Giuseppetm** [comment]
> (sistemo comunque il fatto che premendo da' il reset)

Piccolo update: per ora non riesco a farlo; in ogni caso ho aggiunto il pulsante apposito.

**Comment by Giuseppetm** [comment]
Update:

dato che l'unica sezione che richiede l'inserimento di dati è quella dei gruppi, direi che per ora si può chiudere l'issue.
Con il pulsante apposito per il refresh c'è la possibilità di resettare la pagina; non sono riuscito a modificare il componente nativo per l'update in quanto probabilmente non è stato pensato per ricaricare se ci si trova nella stessa pagina.

Aprirò ugualmente una issue sulla loro repo per vedere se si può aggiungere un'opzione che permette di scegliere il comportamento del pivot.
