### ISSUE TITLE
mostrare il cdl

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#300]
quando arrivo nella pagina dei Gruppi da un link direttto (ad esempio [https://studentiunimi.it/courses/triennale_informatica_com_digitale](https://studentiunimi.it/courses/triennale_informatica_com_digitale)) non viene mostrato il titolo "Informatica per la Comunicazione Digitale"

**Comment by Giuseppetm** [comment]
Già fixato nella #299
