### ISSUE TITLE
upper case slugs don't work

### ISSUE THREAD

**Issue by ranieri-unimi** [StudentiUniMi/website#303]
e.g. nor `/courses/EPS` neither `/courses/eps` load any resources, where the original slug is `EPS`
however `/courses/DSE` and `/courses/dse` work, where the original slug is `dse`

**Comment by Giuseppetm** [comment]
I didn't know about uppercase slugs, if you had warned me earlier I would have handled that case too. 

Fix incoming

**Comment by Giuseppetm** [comment]
It's not a frontend problem, but it's a backend one.

All slugs should be lowercase, otherwise I can't use the toLowerCase to handle cases where the user wants to manually type the url and maybe capitalize randomly.

**Comment by Giuseppetm** [comment]
To be more precise:

# 292 should be removed as a feature in case there are slugs with both uppercase and lowercase letters.
