### ISSUE TITLE
Show Selected Degree in Groups page

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#325]
Show the selected degree in the groups page, something like this:

<img width="876" alt="Screen Shot 2021-12-20 at 10 47 37" src="https://user-images.githubusercontent.com/7923365/146747284-cbe2dfcd-0425-4b15-88f4-1806d0080428.png">

**Comment by Giuseppetm** [comment]
It becomes redundant and it is already displayed here:

![image](https://user-images.githubusercontent.com/52317197/146786273-79c950dc-a284-4d82-b6ca-749ab769feb4.png)

If I display another text I only use space that is really important in mobile view to immediately see groups.
