### ISSUE TITLE
page content doesn't update if I go back

### ISSUE THREAD

**Issue by robertopinotti** [StudentiUniMi/website#329]
I'll explain better with an example

I open the page https://studentiunimi.it/courses/triennale_sicurezza_sistemi_reti_informatiche
I search for another degree, for example "informatica per la comunicazione digitale"
The new url is https://studentiunimi.it/courses/triennale_informatica_com_digitale
If I go back, the url does update but the content of the page doesn't

**Comment by Giuseppetm** [comment]
Related to #23
I'll see if I can fix this
