### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#344]
https://nextjs.org/docs/migrating/from-create-react-app
https://nextjs.org/docs/routing/dynamic-routes
https://github.com/resir014/nextjs-fluentui-quickstart
https://gitlab.com/kachkaev/website-frontend/-/blob/ec20c3bfec24cde40d80194bcad5ba69b308a5ef/src/pages/_document.tsx
https://codesandbox.io/s/xvkrn5wx2p?file=/pages/_document.js:538-664

- [x] Parte di condivisione della struttura base del sito (header, footer, e impostazioni base)
- [x] Sostituzione di react-router con next/router
- [x] Sistemazione dell'helmet (va una funzione che pulisce il tutto e costruisce i metadati + sostituzione con la roba di next)
- [x] #345 
- [x] #346
- [x] Sistemazione vari import per il supporto dell'SSR
- [x] Work around icone non renderizzate e alcuni componenti non funzionanti sul primo render
- [x] Rimozione delle vecchie librerie di font-awesome e icone sparse
- [x] Fix dynamic route per la pagina del cdl
- [x] Nuovo script per il workflow (by @MarcoBuster)
- [x] Add 20 string degrees to API result (by @MarcoBuster)
- [x] Fix su inizializzazione theme e language + cookie server side
- [x] Html lang dinamico
- [x] Ristrutturazione sezione courses
- [x] Rimozione temporanea del routing sulle sezioni services e university
- [x] Uso di un'altra libreria per il react-typed in homepage
- [x] Readme update (specifica il server-side rendering e leva l'api service)

https://github.com/vercel/next.js/discussions/40187
https://github.com/microsoft/fluentui/discussions/24497
https://github.com/resir014/nextjs-fluentui-quickstart/issues/2
https://github.com/microsoft/fluentui/issues/24636

**Comment by MarcoBuster** [comment]
@Giuseppetm
