### ISSUE TITLE
Custom behaviour for card title overflow

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#357]
The text must go multi line and then be truncated with the ...
Use an additional Tooltip in that case

![image](https://user-images.githubusercontent.com/52317197/189535368-28cec1ce-7560-4191-bbd4-bd4300380756.png)

**Comment by MarcoBuster** [comment]
![immagine](https://user-images.githubusercontent.com/14850025/189535446-82f20daf-665c-42c9-bae4-07137253363b.png)
