### ISSUE TITLE
Change degree underscores to hyphens

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#379]
![image](https://user-images.githubusercontent.com/52317197/215709041-e92906fd-b671-47b3-adc4-26676825aaae.png)

@MarcoBuster

**Comment by MarcoBuster** [comment]
I agree, but changing the `/courses/xxx` URLs can be worse for a SEO perspective (and analytics...)

**Comment by Giuseppetm** [comment]
To mantain compatibility with old links that were sent in the groups chats I could replace the undescore with the hyphen server side. Let me know what you think
