### ISSUE TITLE
Change SEO localization behaviour

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#400]
Non-Italian users are a very low percentage so there is no point in taking the language at every request and then rendering it. The performance is still very good but it is not a best practice considering that the site is in fact in Italian by default and can change client-side language if needed.

My proposal is to restore static generation on all pages except for the degree course page that requires ssr.

Pros:
- Extremely high performance;
- Improved SEO.

Cons:
- international users searching for "network studentiunimi" on search engines would get the result in Italian.

## To-do
- [x] Remove global SSR and use italian localization by default;
- [x] Dialog on client-side (first website visit) to suggest language change.

**Comment by MarcoBuster** [comment]
Feature request: at runtime (client-side), read the `Accept-Language` header. If 'italian' is not accepted, show a banner in English to guide the user to change the site language.

Also, enable SSR on degree pages would be crazy too :rocket:. Maybe with periodic (server-side) refreshing to address db updates.
