### ISSUE TITLE
PersonaImage doesn't show correctly on mozilla and probably other browsers

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUnimi/website#74]

**Comment by MarcoBuster** [comment]
Screenshot of the artifact:
![](https://user-images.githubusercontent.com/14850025/108208008-c56fc880-7128-11eb-9b16-05874fd2e6c5.png)

**Comment by Giuseppetm** [comment]
> Screenshot of the artifact:

Thank you, Mr.Aceti.

**Comment by Giuseppetm** [comment]
Apparently it was a singular case.
