### ISSUE TITLE
Add fluent ui's motion to pivot elements

### ISSUE THREAD

**Issue by Giuseppetm** [StudentiUniMi/website#83]
#### These are the few things we know about motion on fluent ui
- https://github.com/microsoft/fluentui/blob/master/packages/react-docsite-components/src/components/Animation/AnimationExample/AnimationExample.tsx

- https://www.c-sharpcorner.com/article/animation-or-motion-effects-using-office-ui-fabric-fluent-ui-in-spfx/

- https://codepen.io/akoltz/pen/QWbWdMO

**Comment by manuelelucchi** [comment]
No u gay

**Comment by Giuseppetm** [comment]
This is closed until Microsoft provides some decent documentation about motion.
