### ISSUE TITLE
Link corso "Sviluppo Di Applicazioni Per Dispositivi Mobili" non funzionante

### ISSUE THREAD

**Issue by albertorizzi** [StudentiUnimi/website#97]
Il link Telegram del corso in oggetto non funziona.
https://t.me/joinchat/AC9fAkhy7f0Hf0b1lu_2VQ

**Comment by Giuseppetm** [comment]
Thank you for reporting the issue.

**Comment by Giuseppetm** [comment]
@albertorizzi Do you have the correct group link?

**Comment by albertorizzi** [comment]
@Giuseppetm unfortunately not..
